### ISSUE TITLE
Unable to parse dot file (other parsers are able to display)

### ISSUE THREAD

**Issue by yizakat** [jrfonseca/xdot.py#112]
Getting "5427:1:unexpected token b'digraph' opening the output from Yosys FGPA synthesis.

The same file can be opened and viewed using VSCode graphviz extensions.

GNU Linux, Ubuntu 2022.10,  (5.15.90.1)

Dot file attached.

[topaz.dot.gz](https://github.com/jrfonseca/xdot.py/files/11316180/topaz.dot.gz)

**Comment by jrfonseca** [comment]
The issue is that this dot file has three graphs concatenated in one file.

If one runs `dot -Tsvg -O topaz.dot` then graphgiz will actually generate 3 different files:  `topaz.dot.svg`, `topaz.dot.2.svg`, and `topaz.dot.3.svg`.

If one runs `dot -Tsvg topaz.dot > topaz.svg`, then graphviz will actually generate an invalid SVG file, with three XML concatenated in the output:

```bash
$ grep '<?xml' topaz.svg 
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
````

https://graphviz.org/doc/info/lang.html doesn't describe this.  But according to https://stackoverflow.com/a/63874856 this is know to work.

I don't know which VSCode plugin you used (there seems to be many), but I suppose it shows only the first graph, no?

At any rate, this seems a weird/rare corner case.  It would be very complicate to make xdot show multiple independent graphs.

At best I could make xdot.py throw a warning and try to gracefully handle this, e.g, by only showing the first.

But I'd recommend avoiding this, and using separate graphs in separate files, at least if you want to use xdot.py

**Comment by yizakat** [comment]
That makes sense and, in any case,  is easy enough to alter the makefile to generate individual outputs.  You are correct that the VSCode plugin only shows one diagram.

Appreciate the fast response.  

Thanks.
