### ISSUE TITLE
xdot does not warn about missing fonts

### ISSUE THREAD

**Issue by SnoopJ** [jrfonseca/xdot.py#117]
When drawing a graph, `xdot` may try to use fonts that are not available on the system, which can lead to graphs like this:

![image of a call graph with "tofu" characters in the labels](https://github.com/jrfonseca/xdot.py/assets/6125322/de137a09-34cc-43a0-853f-99ea536e977a)

In this case, the font `Times-Roman` is specified by [the input file](https://gist.github.com/SnoopJ/2220a066a66c211b4ca8f415f97f1130), but missing on my system. I discovered the issue with `xdot` installed from the Ubuntu 20.04 package, but I can reproduce it with a copy installed from PyPI as well.

It would be nice if `xdot` issued a warning in cases like this so that the user has a hint about what went wrong, or if it could fall back onto a default font (although doing this in a portable way that still looks good is probably tricky).

**Comment by jrfonseca** [comment]
Per https://graphviz.org/faq/font/ `Times-Roman` is the default font, and `fontconfig` should automatically map it to the closest font.  It's odd your system doesn't have it.

Still I agree, a warning would be nice.

I don't have the time to look into this but I'd happily accept a PR.

**Comment by SnoopJ** [comment]
> It's odd your system doesn't have [fontconfig]

Interestingly, I _do_ have `fontconfig` installed, but I guess something is preventing fallback to an available font when generating the graph. I wonder if that's an idiosyncrasy of Ubuntu packaging.

> Still I agree, a warning would be nice.
> 
> I don't have the time to look into this but I'd happily accept a PR.

I experimented a little bit with adding behavior along these lines, I think I see how to do it, will file a PR once I have all the details together. I don't know if there's a good way to determine a fallback font family, but in my experiment I fell back on the `Sans` family with decent results.

**Comment by jrfonseca** [comment]
I'm hitting this problem myself after upgrading to Ubuntu 24.04.

The issue is that Pango doesn't seem to be calling fontconfig to do the mapping.

However https://github.com/jrfonseca/xdot.py/pull/118 has a few issues:
- the default `Times-Roman` is not mapped to a serif font
- per https://graphviz.org/docs/attrs/fontname/ `fontname` is not just a family name, it could even be a pango description

I tackled this differently on d4785bb409d755b7e7492cdb5ab5e3fe69640c12.  I hope it still works for you.
