### ISSUE TITLE
xdot imports gi, which is not available for python3.9.1.0

### ISSUE THREAD

**Issue by jrbrearley** [jrfonseca/xdot.py#88]
xdot-1.2.tar from pypi.org will install via the WinPyton Control Panel. However, from the IDLE GUI shell, import xdot fails with:

Traceback (most recent call last):
  File "<pyshell#24>", line 1, in <module>
    import xdot
  File "C:\WinPython\python-3.9.1.amd64\lib\site-packages\xdot\__init__.py", line 26, in <module>
    from . import ui
  File "C:\WinPython\python-3.9.1.amd64\lib\site-packages\xdot\ui\__init__.py", line 3, in <module>
    from .window import DotWidget, DotWindow
  File "C:\WinPython\python-3.9.1.amd64\lib\site-packages\xdot\ui\window.py", line 25, in <module>
    import gi

Manual search of pypi.org for gi shows nothing. From WinPython Command Prompt, pip3 install gi fails with:
ERROR: Could not find a version that satisfies the requirement gi
ERROR: No matching distribution found for gi

pip install gi gets the same error.

Is xdot really supported on python3? If not please update pipy.org & other docs to show python2 only / depracated.

**Comment by jrfonseca** [comment]
xdot.py depends on PyGObject bindings for GTK3, which are not available on PyPi.  One needs to install them separately.

Please follow the links on https://github.com/jrfonseca/xdot.py#windows-users , particularly https://pygobject.readthedocs.io/en/latest/getting_started.html#windows-getting-started

I know getting PyGObject bindings for GTK3 is not easy on Windows as it is on Linux, but I'm afraid there's no alternative.  (If I were to start this again, I'd probably use Qt instead of GTK, but that ship has sailed.)

I think I'll update the source code to point automatically to the docs.
